In [4]:
import numpy as np

[1 2 3 4]


In [6]:
a=[1,2,3,'hello']
print(a)

[1, 2, 3, 'hello']


In [10]:
arr=np.array(a)
arr

array(['1', '2', '3', 'hello'], dtype='<U21')

In [37]:
arr=np.arange(1,31)
a=arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [44]:
slice=a[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [61]:
arr=np.arange(1,11)
slice = arr[:5]
slice=slice*10
slice
arr=arr*10
print(arr)
slice

[ 10  20  30  40  50  60  70  80  90 100]


array([10, 20, 30, 40, 50])

In [112]:
a=np.array([[1,-1,-3],[4,0,5],[38,3,5]])
a

array([[ 1, -1, -3],
       [ 4,  0,  5],
       [38,  3,  5]])

In [113]:
slice=a[0:2,1:3]
slice

array([[-1, -3],
       [ 0,  5]])

In [124]:
a=np.arange(1,31)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [126]:
bool=a%2!=0
bool

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False])

In [127]:
a=a[bool]
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [143]:
a1=np.array([1,2,3,4,5])
a1+10
a2=np.array([6,7,8,9,10])
a1

array([1, 2, 3, 4, 5])

In [146]:
l=[1,2,3,4,5]
a=np.array(l)
a+10

array([11, 12, 13, 14, 15])

In [148]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])

array([[1, 2],
       [3, 4]])

In [150]:
a1*a2

array([[ 5, 12],
       [21, 32]])

In [151]:
a1@a2

array([[19, 22],
       [43, 50]])

In [152]:
a1.T

array([[1, 3],
       [2, 4]])

In [170]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
arr=np.vstack([a,b])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [178]:
sp=np.hsplit(arr,4)
sp

[array([[1],
        [5]]),
 array([[2],
        [6]]),
 array([[3],
        [7]]),
 array([[4],
        [8]])]